config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  devise_for :users, controllers: {:registrations => "registrations",sessions: "sessions"}

  root 'welcomes#home'
  get "/welcomes/user" => "welcomes#user", :as => "user"
  get "/welcomes/home" => "welcomes#home", :as => "home"

  get "/book_events/event_image" => "book_events#event_image"
  get "/book_events/view_event_detail" => "book_events#view_event_detail"
  get "/book_events/booking_history" => "book_events#booking_history", :as => "booking_history"
  get "/book_events/booking_status" => "book_events#booking_status", :as => "booking_status"
  get "/book_events/function_price" => "book_events#function_price", :as => "function_price"
  post "/book_events/create_events" => "book_events#create_events", :as => "create_events"
  get "/book_events/new_event" => "book_events#new_event", :as => "new_event"
  get "/book_events/event_details" => "book_events#event_details", :as => "event_details"
  resources :book_events, :only=>[:index,:new]

  get "/events/venue_image" => "events#venue_image", :as => "venue_image"
  post "/events/save_venue_image" => "events#save_venue_image", :as => "save_venue_image"
  get "/events/event_image" => "events#event_image", :as => "event_image"
  get "/events/view_event_detail" => "events#view_event_detail", :as => "view_event_detail"
  get "/events/view_booking" => "events#view_booking", :as => "view_booking"
  get "/events/update_booking" => "events#update_booking", :as => "update_booking"
  get "/events/new_booking" => "events#new_booking", :as => "new_booking"
  get "/events/venue_address" => "events#venue_address", :as => "venue_address"
  post "/events/create_event" => "events#create_event", :as => "create_event"
  get "/events/add_event" => "events#add_event", :as => "add_event"
  get "/events/event_detail" => "events#event_detail", :as => "event_detail"

  get "/events/edit_event_detail" => "events#edit_event_detail", :as => "edit_event_detail"
  post "/events/update_event_detail" => "events#update_event_detail", :as => "update_event_detail"
  get "/events/delete_event_detail" => "events#delete_event_detail", :as => "delete_event_detail"

  get "/events/add_venue" => "events#add_venue", :as => "add_venue"
  post "/events/create_venue" => "events#create_venue", :as => "create_venue"
  get "/events/show_venue" => "events#show_venue", :as => "show_venue"
  get "/events/edit_venue" => "events#edit_venue", :as => "edit_venue"
  post "/events/update_venue" => "events#update_venue", :as => "update_venue"
  get "/events/delete_venue" => "events#delete_venue", :as => "delete_venue"
  get "/events/venue" => "events#venue", :as => "venue"
  post "/events/create_price" => "events#create_price", :as => "create_price"
  get "/events/add_price" => "events#add_price", :as => "add_price"
  get "/events/price" => "events#price", :as => "price"
  get "/events/edit_price" => "events#edit_price", :as => "edit_price"
  post "/events/update_price" => "events#update_price", :as => "update_price"
  get "/events/delete_price" => "events#delete_price", :as => "delete_price"
  post "/events/create_function" => "events#create_function", :as => "create_function"
  get "/events/function" => "events#function", :as => "function"
  get "/events/venue_detail" => "events#venue_detail", :as => "venue_detail"
  get "/events/edit_function" => "events#edit_function", :as => "edit_function"
  post "/events/update_function" => "events#update_function", :as => "update_function"
  get "/events/delete_function" => "events#delete_function", :as => "delete_function"
  resources :events, :only=>[:index,:new]

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  def index
    @feedbacks = Feedback.all
    render :layout => 'admin_layout'
  end

  # def show
  # end

  def new
    @feedback = Feedback.new
    render :layout => 'customer_layout'
  end

  # def edit
  # end

  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to :back, notice: 'Feedback was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @feedback.update(feedback_params)
  #       format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @feedback }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @feedback.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    @feedback.destroy
      flash[:notice]= 'Feedback was successfully destroyed.'
      redirect_to :action=>'index'
  end

  private
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    def feedback_params
      params.require(:feedback).permit(:user_id, :feedback, :date, :email)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <%=f.hidden_field :user_id, :value => current_user.id%>
  <%=f.hidden_field :date, :value =>  DateTime.now.to_date%>
  <%=f.hidden_field :email, :value => current_user.email%>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%#= f.label :user_id %><br>
    <%#= f.number_field :user_id %>
  </div> -->
  <div class="field">
    <%= f.label :feedback %><br>
    <%= f.text_area :feedback %>
  </div>
  <!-- <div class="field">
    <%#= f.label :date %><br>
    <%#= f.date_select :date %>
  </div>
  <div class="field">
    <%#= f.label :email %><br>
    <%#= f.text_field :email %>
  </div> -->
  <div class="actions">
    <%= f.submit 'Submit', :class => 'submit' %>
  </div>
<% end %>

app/views/feedbacks/index.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<h1>Feedbacks</h1>
<%if @feedbacks.length>0%>
  <table class="event-table">
    <thead>
      <tr>
        <th>Feedback</th>
        <th>Date</th>
        <th>Email</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @feedbacks.each do |feedback| %>
        <tr>
          <td><%= feedback.feedback %></td>
          <td><%= feedback.date %></td>
          <td><%= feedback.email %></td>
          <td><%= link_to 'Delete', feedback, method: :delete, data: { confirm: 'Are you sure?' },:class => 'submit' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%else%>
  <%="No FeedBacks"%>
<%end%>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/zedit.html.erb
<%#= render 'form' %>

<%#= link_to 'Show', @feedback %> |
<%#= link_to 'Back', feedbacks_path %>

app/views/feedbacks/zshow.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @feedback.feedback %>
</p>

<p>
  <strong>Date:</strong>
  <%= @feedback.date %>
</p>

<p>
  <strong>Email:</strong>
  <%= @feedback.email %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>